src/objects/Certification__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Certification</label>
    <nameField>
        <label>Certificate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Competency__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Competencies</relationshipLabel>
        <relationshipName>Competencies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score (Out of 100)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Competency</label>
    <nameField>
        <label>Competency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Photo_URL__c</fullName>
        <label>Photo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>UID__c</fullName>
        <externalId>true</externalId>
        <label>UID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Education__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Educations</relationshipLabel>
        <relationshipName>Educations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPA__c</fullName>
        <label>GPA</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>School_Name__c</fullName>
        <label>School Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Education</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Key_Expertise__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Key Expertises</relationshipLabel>
        <relationshipName>Key_Expertises</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score (Out of 100)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Key Expertise</label>
    <nameField>
        <label>Key Expertise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Expertises</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reference__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>References</relationshipLabel>
        <relationshipName>References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MailTo__c</fullName>
        <formula>&quot;mailto:&quot; + Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MailTo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Photo_URL__c</fullName>
        <label>Photo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Reference</label>
    <nameField>
        <label>Referrer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Social_Handle__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Social Handles</relationshipLabel>
        <relationshipName>Social_Handles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Handle_Icon__c</fullName>
        <label>Handle Icon</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Handle_Link__c</fullName>
        <label>Handle Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Social Handle</label>
    <nameField>
        <label>Social Handle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Social Handles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trailhead_Superbadge__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Trailhead Superbadges</relationshipLabel>
        <relationshipName>Trailhead_Superbadges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Favourite__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Favourite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Superbadge_Description__c</fullName>
        <label>Superbadge Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Superbadge_Image__c</fullName>
        <label>Superbadge Image</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Superbadge_Link__c</fullName>
        <label>Superbadge Link</label>
        <type>Url</type>
    </fields>
    <label>Trailhead Superbadge</label>
    <nameField>
        <label>Superbadge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailhead Superbadges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Work_Experience__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Work Experiences</relationshipLabel>
        <relationshipName>Work_Experiences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Responsibilities__c</fullName>
        <label>Responsibilities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Work Experience</label>
    <nameField>
        <label>Job Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ResumeAPI.cls
public with sharing class ResumeAPI {
    public class Response {
        @AuraEnabled public Boolean isSuccess;
        @AuraEnabled public String message;
        @AuraEnabled public Object data;

        public Response( Boolean isSuccess, String message, Object data ) {
            this.isSuccess = isSuccess;
            this.message = message;
            this.data = data;
        }
    }

    public class Resume {
        @AuraEnabled public Contact basicInfo;
        @AuraEnabled public List<Reference__c> references;
        @AuraEnabled public List<Key_Expertise__c> keyExpertises;
        @AuraEnabled public List<Education__c> educations;
        @AuraEnabled public List<Social_Handle__c> socialHandles;
        @AuraEnabled public List<Competency__c> competencies;
        @AuraEnabled public List<Certification__c> certifications;
        @AuraEnabled public List<Trailhead_Superbadge__c> trailheadSuperbadges;
        @AuraEnabled public List<Work_Experience__c> workExperiences;
    }

    @AuraEnabled( cacheable = TRUE )
    public static List<Social_Handle__c> getSocialHandles( String recordId ) {
        if( !String.isBlank( recordId ) ) {
            List<Social_Handle__c> records = new List<Social_Handle__c>();

            records = [
                SELECT  Name
                        ,Handle_Link__c
                        ,Handle_Icon__c
                FROM    Social_Handle__c
                WHERE   Contact__c = :recordId
            ];

            if( !records.isEmpty() ) {
                return records;
            }
        }

        return new List<Social_Handle__c>();
    }

    @AuraEnabled( cacheable = TRUE )
    public static List<Trailhead_Superbadge__c> getFavSuperbadge( String recordId ) {
        if( !String.isBlank( recordId ) ) {
            List<Trailhead_Superbadge__c> records = new List<Trailhead_Superbadge__c>();

            records = [
                SELECT  Name
                        ,Superbadge_Image__c
                        ,Superbadge_Description__c
                        ,Superbadge_Link__c
                FROM    Trailhead_Superbadge__c
                WHERE   Contact__c = :recordId AND
                        Favourite__c = TRUE
            ];

            if( !records.isEmpty() ) {
                return records;
            }
        }

        return new List<Trailhead_Superbadge__c>();
    }

    @AuraEnabled( cacheable = TRUE )
    public static List<Key_Expertise__c> getKeyExpertises( String recordId ) {
        if( !String.isBlank( recordId ) ) {
            List<Key_Expertise__c> records = new List<Key_Expertise__c>();

            records = [
                SELECT      Name
                            ,Score__c
                FROM        Key_Expertise__c
                WHERE       Contact__c = :recordId
            ];

            if( !records.isEmpty() ) {
                return records;
            }
        }

        return new List<Key_Expertise__c>();
    }

    @AuraEnabled( cacheable = TRUE )
    public static List<Reference__c> getReferences( String recordId ) {
        if( !String.isBlank( recordId ) ) {
            List<Reference__c> records = new List<Reference__c>();

            records = [
                SELECT  Name
                        ,Company__c
                        ,MailTo__c
                        ,Relationship__c
                        ,Photo_URL__c
                FROM    Reference__c
                WHERE   Contact__c = :recordId
            ];

            if( !records.isEmpty() ) {
                return records;
            }
        }

        return new List<Reference__c>();
    }

    @AuraEnabled( cacheable = TRUE )
    public static List<Certification__c> getCertifications( String recordId ) {
        if( !String.isBlank( recordId ) ) {
            List<Certification__c> records = new List<Certification__c>();

            records = [
                SELECT      Name
                            ,Release__c
                FROM        Certification__c
                WHERE       Contact__c = :recordId
                ORDER BY    Order__c ASC
            ];

            if( !records.isEmpty() ) {
                return records;
            }
        }

        return new List<Certification__c>();
    }

    @AuraEnabled( cacheable = TRUE )
    public static List<Work_Experience__c> getWorkExperiences( String recordId ) {
        if( !String.isBlank( recordId ) ) {
            List<Work_Experience__c> records = new List<Work_Experience__c>();

            records = [
                SELECT      Name
                            ,Company__c
                            ,Duration__c
                            ,Responsibilities__c
                FROM        Work_Experience__c
                WHERE       Contact__c = :recordId
                ORDER BY    Order__c ASC
            ];

            if( !records.isEmpty() ) {
                return records;
            }
        }

        return new List<Work_Experience__c>();
    }

    @AuraEnabled( cacheable = TRUE )
    public static List<Education__c> getEducations( String recordId ) {
        if( !String.isBlank( recordId ) ) {
            List<Education__c> records = new List<Education__c>();

            records = [
                SELECT      Name
                            ,School_Name__c
                            ,Duration__c
                            ,GPA__c
                FROM        Education__c
                WHERE       Contact__c = :recordId
                ORDER BY    Order__c ASC
            ];

            if( !records.isEmpty() ) {
                return records;
            }
        }

        return new List<Education__c>();
    }

    @AuraEnabled( cacheable = TRUE )
    public static List<Competency__c> getCompetencies( String recordId ) {
        if( !String.isBlank( recordId ) ) {
            List<Competency__c> records = new List<Competency__c>();

            records = [
                SELECT      Name
                            ,Score__c
                FROM        Competency__c
                WHERE       Contact__c = :recordId
            ];

            if( !records.isEmpty() ) {
                return records;
            }
        }

        return new List<Competency__c>();
    }

    @AuraEnabled( cacheable = FALSE )
    public static Response loadSampleData( String data ) {
        try {
            String jsonStr = EncodingUtil.base64Decode( data ).toString();

            Resume cv = ( Resume ) JSON.deserialize(
                jsonStr,
                Resume.class
            );

            Contact con = cv.basicInfo;
            con.UID__c = 1;

            Contact conRef = new Contact( UID__c = 1 );

            for( Reference__c ref : cv.references ) {
                ref.Contact__r = conRef;
            }

            for( Key_Expertise__c keyExp : cv.keyExpertises ) {
                keyExp.Contact__r = conRef;
            }

            for( Education__c edu : cv.educations ) {
                edu.Contact__r = conRef;
            }

            for( Social_Handle__c soc : cv.socialHandles ) {
                soc.Contact__r = conRef;
            }

            for( Competency__c comp : cv.competencies ) {
                comp.Contact__r = conRef;
            }

            for( Certification__c cert : cv.certifications ) {
                cert.Contact__r = conRef;
            }

            for( Trailhead_Superbadge__c th : cv.trailheadSuperbadges ) {
                th.Contact__r = conRef;
                th.Favourite__c = TRUE;
            }

            for( Work_Experience__c exp : cv.workExperiences ) {
                exp.Contact__r = conRef;
            }

            List<SObject> records = new List<SObject>();
            records.add( con );
            records.addAll( ( List<SObject> ) cv.references );
            records.addAll( ( List<SObject> ) cv.keyExpertises );
            records.addAll( ( List<SObject> ) cv.educations );
            records.addAll( ( List<SObject> ) cv.socialHandles );
            records.addAll( ( List<SObject> ) cv.competencies );
            records.addAll( ( List<SObject> ) cv.certifications );
            records.addAll( ( List<SObject> ) cv.trailheadSuperbadges );
            records.addAll( ( List<SObject> ) cv.workExperiences );

            INSERT records;

            return new Response( TRUE, 'Sample data has been loaded successfully.', NULL );
        }
        catch( Exception ex ) {
            return new Response( FALSE, 'Error - ' + ex.getMessage(), NULL );
        }
    }
}